### ISSUE TITLE
Add option to change the "add to cart" text

### ISSUE THREAD

**Issue by yakovsh** [impossibledreams/wc-external-variations#3]
Ideally a global configuration with an override within each external variation. Because of the way the WooCommerce hooks work, the override would have to be implemented in JavaScript

**Comment by phofm** [comment]
Hi @yakovsh. This would be an excellent addition! The UX when clicking on the button and then being taken to an external page has proved highly confusing in our tests.

Thanks for your great plugin!

**Comment by yakovsh** [comment]
Added in v1.0.7
